config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  resources :users, only: [:index, :show, :update]
  delete 'users/delete_user/:id', to: 'users#delete_user'
  
  get 'home/index'
  root 'home#index'
  resources :posts
  get '/user_posts/:user_name', to: 'posts#user_posts', as: :user_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  # validates :math, presence: true
  # validates :english, presence: true
  # validates :science, presence: true
  # validates :period, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ayan_posts = Post.joins(:user).where(users: { name: "Ayan" })
    @anam_posts = Post.joins(:user).where(users: { name: "Anam" })
    @neha_posts = Post.joins(:user).where(users: { name: "Neha" })
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).order(:created_at)
    @user_names = User.pluck(:name).uniq

    # Check if a user name is selected from the dropdown
    if params[:user_name].present?
      @user_posts = @posts.where(user: User.where(name: params[:user_name]))
    else
      @user_posts = @posts
    end
  end

  def user_posts
    @user_name = params[:user_name]
    @user = User.find_by(name: @user_name)
    @user_posts = @user.posts.includes(:user) if @user
    respond_to do |format|
      format.json { render json: @user_posts }
      format.html { }
    end
  end

  def by_date
    desired_date = Date.parse('2023-07-18')
    @posts = Post.where(date: desired_date)
  end

  def by_time
    desired_time = Time.parse('14:30:00')
    @posts = Post.where(time: desired_time)
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:math, :science, :english, :period, :user_id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # skip_before_action :verify_authenticity_token, only: :create

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    user = User.find_by(email: params[:user][:email])
    if user&.valid_password?(params[:user][:password])
      sign_in(user) # This signs in the user
      render json: { message: 'Logged in successfully.' }, status: :ok
    else
      render json: { error: 'Invalid email or password.' }, status: :unauthorized
    end
  end


  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # DELETE /users/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  protected

  def respond_to_on_destroy
    render json: { message: 'Logged out successfully.' }, status: :no_content
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_user_signed_in
  before_action :check_admin, only: [:update, :delete_user]
  
  def index
    @users = User.all
    render json: @users
  end

  def show
    user = User.find(params[:id])
    render json: user
  end
  
  def update
    user = User.find(params[:id])
    if user.update(user_params)
      render json: user
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def delete_user
    user = User.find(params[:id])
    if user.destroy
      render json: {message: "User deleted successfully!"}
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def check_user_signed_in
    unless user_signed_in?
      render json: { message: "Please sign in." }, status: :unauthorized
    end
  end

  def check_admin
    unless current_user&.admin?
      render json: { message: "You are not authorized to perform this action." }, status: :unauthorized
    end
  end

  def user_params
    params.require(:user).permit(:name, :user_type, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="home-index">
  <h1 class="heading">Welcome to the Task App!</h1>
  <div class="home-index-container">
    <div class="home-index-btns">
      <div class="home-index-btn">
        <%= link_to "Neha", user_posts_path(user_name: 'Neha'), class: "btn" %>
      </div>
      <div class="home-index-btn">
        <%= link_to "Anam", user_posts_path(user_name: 'Anam'), class: "btn" %>
      </div>
      <div class="home-index-btn">
        <%= link_to "Ayan", user_posts_path(user_name: 'Ayan'), class: "btn" %>
      </div>
    </div>
    <div>
      <%= link_to 'New Post', new_post_path %><br>
      <%= link_to 'Index', posts_path %><br>
      <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/by_name.html.erb
<h1><%= @posts_by_name.first.name %>'s posts</h1>
<% if @posts_by_name.any? %>
  <ul>
    <% @posts_by_name.each do |post| %>
      <li>Date: <%= post.date %>, Time: <%= post.time %>,  Period: <%= post.period %></li>
      <li>English: <%= post.english %></li>
      <li>Math: <%= post.math %></li>
      <li>Science: <%= post.science %></li>
    <% end %>
  </ul>
<% else %>
  <p>No posts with the name "<%= @posts_by_name.first.name %>" has no post.</p>
<% end %>

app/views/posts/index.html.erb
<div class="container mx-auto p-4">
  <!-- Add the dropdown to filter posts by user's name -->
  <%= form_with(url: posts_path, method: :get, local: true) do |f| %>
    <div class="mb-4">
      <%= f.label :user_name, "Filter by User's Name", class: "font-medium" %><br />
      <%= f.select :user_name, options_for_select(@user_names), { prompt: "All Users" }, class: "mt-1 p-2 w-full rounded border-gray-300" %>
    </div>

    <div class="mb-4">
      <%= f.submit "Filter", class: "bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded" %>
    </div>
  <% end %>

  <h1 class="text-4xl font-bold mb-4">All Posts</h1>
  <ul>
    <% @user_posts.each do |post| %>
      <li class="bg-gray-100 rounded p-4 mb-4">
        <strong><%= post.user.name %></strong> | Period: <%= post.period %>
        <ul class="pl-6 text-gray-600">
          <li>English: <%= post.english %></li>
          <li>Math: <%= post.math %></li>
          <li>Science: <%= post.science %></li>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<h1 class="text-2xl font-bold mb-4 text-center m-10">Create a New Post</h1>

<%= form_with(model: @post, url: posts_path, class: "space-y-4") do |form| %>
  <div class="flex flex-col">
    <%= form.label :english, class: "text-lg font-semibold mb-2" %>
    <%= form.text_field :english, class: "border p-2 rounded-lg focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="flex flex-col">
    <%= form.label :math, class: "text-lg font-semibold mb-2" %>
    <%= form.text_field :math, class: "border p-2 rounded-lg focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="flex flex-col">
    <%= form.label :science, class: "text-lg font-semibold mb-2" %>
    <%= form.text_field :science, class: "border p-2 rounded-lg focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="flex flex-col">
    <%= form.label :period, class: "text-lg font-semibold mb-2" %>
    <%= form.text_field :period, class: "border p-2 rounded-lg focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="flex justify-center">
    <%= form.submit "Create", class: "bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring focus:border-blue-300" %>
  </div>
<% end %>

<%= link_to 'Back', posts_path, class: "block text-center mt-4 text-blue-500 hover:text-blue-700" %>

app/views/posts/user_posts.html.erb
<div class="user-posts bg-gray-100 p-6 rounded-lg shadow-lg">
  <h1 class="text-3xl font-bold mb-4 text-center"><%= @user_name %>'s Posts</h1>
  <ul class="space-y-6">
    <% @user_posts.each do |post| %>
      <li class="bg-white rounded-lg shadow-md px-6 py-4">
        <div class="flex items-center justify-between mb-3">
          <div class="text-gray-600">Date & Time <%= post.created_at.strftime("%Y-%m-%d %H:%M:%S")  %></div>
          <div class="text-gray-600">Period: <%= post.period %></div>
        </div>
        <div class="grid grid-cols-1 gap-4">
          <div>
            <div class="font-semibold">English:</div>
            <div><%= post.english %></div>
          </div>
          <div>
            <div class="font-semibold">Math:</div>
            <div><%= post.math %></div>
          </div>
          <div>
            <div class="font-semibold">Science:</div>
            <div><%= post.science %></div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>